version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webtop
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: [webnet]

  backend:
    build: ./backend
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/webtop?sslmode=disable
      - JWT_SECRET=supersecretkey
      - PORTAINER_URL=http://portainer:9000/api
      - PORTAINER_KEY=changeme
    ports: ["8080:8080"]
    depends_on: [postgres, portainer]
    networks: [webnet]

  frontend:
    build: ./frontend
    ports: ["80:80"]
    depends_on: [backend]
    networks: [webnet]

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks: [webnet]

  traefik:
    image: traefik:v3.0
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports: ["8081:8080"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks: [webnet]

volumes:
  pgdata:
  portainer_data:

networks:
  webnet:
